---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-pv-claim
spec:
  storageClassName: jupyterhub-dev
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 9Gi
---

